name: Build Re:VIEW to make distribution file
# The workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Uses the current stable major version
    # https://github.com/actions/checkout
    - name: checkout source
      uses: actions/checkout@v6
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 20
        cache: npm
    - name: Install npm dependencies
      run: npm ci
    - name: Check manuscript wording with prh
      run: npm run check:prh
    # Build Artifacts
    - name: Build distribution file
      uses: TechBooster/ReVIEW-build-artifact-action@master
    # Upload Distribution file
    - name: Upload distribution file to github artifacts
      uses: actions/upload-artifact@v6
      with:
        name: Output documents
        path: ./articles/*.pdf
